insert into tab_especialidades (especialidade, id)  VALUES ('ADMINISTRADOR ', 1);
insert into tab_especialidade  (especialidade, id)  VALUES ('ADMINISTRADOR DE EDIFICIO ', 2);
insert into tab_especialidade  (especialidade, id)  VALUES ('ADMINISTRADOR DE EXPLORACAO AGRICOLA ', 3);
insert into tab_especialidade  (especialidade, id)  VALUES ('ADMINISTRADORES ', 4);
insert into tab_especialidade  (especialidade, id)  VALUES ('ADVOGADO ', 5);
insert into tab_especialidade  (especialidade, id)  VALUES ('ADVOGADO DIREITO DO TRABALHO ', 6);
insert into tab_especialidade  (especialidade, id)  VALUES ('AGENCIADOR DE PROPAGANDA ', 7);
insert into tab_especialidade  (especialidade, id)  VALUES ('AGENTE ADMINISTRATIVO ', 8);
insert into tab_especialidade  (especialidade, id)  VALUES ('AGENTE DE COMPRAS ', 9);
insert into tab_especialidade  (especialidade, id)  VALUES ('AGENTE DE VENDA DE SERVICOS AS EMPRESAS ', 10);
insert into tab_especialidade  (especialidade, id)  VALUES ('AGENTE DE VIAGEM ', 11);
insert into tab_especialidade  (especialidade, id)  VALUES ('AGENTE PUBLICITARIO ', 12);
insert into tab_especialidade  (especialidade, id)  VALUES ('AGENTE TECNICO DE VENDAS ', 13);
insert into tab_especialidade  (especialidade, id)  VALUES ('AGENTES ADMINISTRATIVOS ', 14);
insert into tab_especialidade  (especialidade, id)  VALUES ('AGENTES DE ADMINISTRACAO DE EMPRESAS PUBLICAS E PRIVADAS ', 15);
insert into tab_especialidade  (especialidade, id)  VALUES ('ALMOXARIFE ', 16);
insert into tab_especialidade  (especialidade, id)  VALUES ('ANALISTA DE CARGOS E SALARIOS ', 17);
insert into tab_especialidade  (especialidade, id)  VALUES ('ANALISTA DE COMERCIALIZACAO ', 18);
insert into tab_especialidade  (especialidade, id)  VALUES ('ANALISTA DE COMUNICACA 8234    ANALISTA DE CREDITO E COBRANCA ', 19);
insert into tab_especialidade  (especialidade, id)  VALUES ('ANALISTA DE IMPORTACAO E EXPORTACAO ', 20);
insert into tab_especialidade  (especialidade, id)  VALUES ('ANALISTA DE OCUPACAO ', 21);
insert into tab_especialidade  (especialidade, id)  VALUES ('ANALISTA DE ORGANIZACAO E METODOS ', 22);
insert into tab_especialidade  (especialidade, id)  VALUES ('ANALISTA DE PESQUISA DE MERCADO ', 23);
insert into tab_especialidade  (especialidade, id)  VALUES ('ANALISTA DE RECURSOS HUMANOS ', 24);
insert into tab_especialidade  (especialidade, id)  VALUES ('ANALISTA DE SEGUROS ', 25);
insert into tab_especialidade  (especialidade, id)  VALUES ('ANALISTA DE SISTEMAS ', 26);
insert into tab_especialidade  (especialidade, id)  VALUES ('ANALISTA DE SUPORTE DE SISTEMA ', 27);
insert into tab_especialidade  (especialidade, id)  VALUES ('APONTADOR DE MAO DE OBRA ', 28);
insert into tab_especialidade  (especialidade, id)  VALUES ('APONTADOR DE PRODUCAO ', 29);
insert into tab_especialidade  (especialidade, id)  VALUES ('ARQUITETO ', 30);
insert into tab_especialidade  (especialidade, id)  VALUES ('ARQUIVISTA ', 31);
insert into tab_especialidade  (especialidade, id)  VALUES ('ASSISTENTE ADMINISTRATIVO ', 32);
insert into tab_especialidade  (especialidade, id)  VALUES ('ASSISTENTE DE PATRIMONIO ', 33);
insert into tab_especialidade  (especialidade, id)  VALUES ('ASSISTENTE DE VENDAS FINANCEIRO ', 34);
insert into tab_especialidade  (especialidade, id)  VALUES ('ASSISTENTE SOCIAL ', 35);
insert into tab_especialidade  (especialidade, id)  VALUES ('ATENDETE DE ENFERMAGEM ', 36);
insert into tab_especialidade  (especialidade, id)  VALUES ('ATLETA PROFISSIONAL DE FUTEBOL ', 37);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUDITOR CONTABIL ', 38);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUDITOR GERAL ', 39);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUXILIAR DE ALMOXARIFADO ', 40);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUXILIAR DE BIBLIOTECA ', 41);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUXILIAR DE CONTABILIDADE ', 42);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUXILIAR DE ENFERMAGEM ', 43);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUXILIAR DE ESCRITORIO ', 44);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUXILIAR DE FARMACIA ', 45);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUXILIAR DE IMPORTACAO E EXPORTACAO ', 46);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUXILIAR DE LABORATORIO DE ANALISES CLINICAS ', 47);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUXILIAR DE LABORATORIO DE ANALISES FISICOQUIMICAS ', 48);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUXILIAR DE PESSOAL ', 49);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUXILIAR DE SEGUROS ', 50);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUXILIAR DE SERVICOS JURIDICOS ', 51);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUXILIARES DE CONTABILIDADE ', 52);
insert into tab_especialidade  (especialidade, id)  VALUES ('AUXILIARES DE ESCRITORIO ', 53);
insert into tab_especialidade  (especialidade, id)  VALUES ('BABA ', 54);
insert into tab_especialidade  (especialidade, id)  VALUES ('BARMAN ', 55);
insert into tab_especialidade  (especialidade, id)  VALUES ('BIBLIOTECARIO ', 56);
insert into tab_especialidade  (especialidade, id)  VALUES ('BIOLOGISTA ', 57);
insert into tab_especialidade  (especialidade, id)  VALUES ('BIOQUIMICO ', 58);
insert into tab_especialidade  (especialidade, id)  VALUES ('CABELEIREIRO ', 59);
insert into tab_especialidade  (especialidade, id)  VALUES ('CARTEIRO ', 60);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE ADMINISTRATIVOS ', 61);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE ALMOXARIFADO ', 62);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE CONTABILIDADE ', 63);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE CONTABILIDADE E FINANCAS ', 64);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE CONTAS A PAGAR ', 65);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE CONTROLE DE PATRIMONIO ', 66);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE ESCRITORIO ', 67);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE ESCRITORIO CONTABILIDADE ', 68);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE ESCRITORIO CREDITO E COBRANCA ', 69);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE ESCRITORIO ORCAMENTO ', 70);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE ESCRITORIO PESSOAL ', 71);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE ESCRITORIO SERVICOS GERAIS ', 72);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE ESCRITORIO TESOURARIA ', 73);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE RECEPCAO HOTEL ', 74);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE SERVICO DE TRANSPORTE RODOVIARIO ', 75);
insert into tab_especialidade  (especialidade, id)  VALUES ('CHEFE DE SERVICOS DE TELECOMUNICACOES ', 76);
insert into tab_especialidade  (especialidade, id)  VALUES ('CIRURGIAO ', 77);
insert into tab_especialidade  (especialidade, id)  VALUES ('CIRURGIAO DENTISTA ', 78);
insert into tab_especialidade  (especialidade, id)  VALUES ('CODIFICADOR DE DADOS ', 79);
insert into tab_especialidade  (especialidade, id)  VALUES ('COMERCIANTE VAREJISTA ', 80);
insert into tab_especialidade  (especialidade, id)  VALUES ('COMISSARIO DE BORDO AERONAVES ', 81);
insert into tab_especialidade  (especialidade, id)  VALUES ('COMPRADOR COMERCIO ATACADISTA E VAREJISTA ', 82);
insert into tab_especialidade  (especialidade, id)  VALUES ('CONDUTOR DE CAMINHAO BASCULANTE ', 83);
insert into tab_especialidade  (especialidade, id)  VALUES ('CONDUTORES DE AUTOMOVEIS ', 84);
insert into tab_especialidade  (especialidade, id)  VALUES ('CONSULTOR JURIDICO ', 85);
insert into tab_especialidade  (especialidade, id)  VALUES ('CONTADOR ', 86);
insert into tab_especialidade  (especialidade, id)  VALUES ('CONTRAMESTRE DE EMBARCACAO ', 87);
insert into tab_especialidade  (especialidade, id)  VALUES ('CONTRAMESTRE INDUSTRIA TEXTIL ', 88);
insert into tab_especialidade  (especialidade, id)  VALUES ('COORDENADOR DE ENSINO ', 89);
insert into tab_especialidade  (especialidade, id)  VALUES ('CORRESPONDENTE COMERCIAL ', 90);
insert into tab_especialidade  (especialidade, id)  VALUES ('COZINHEIRO CHEFE ', 91);
insert into tab_especialidade  (especialidade, id)  VALUES ('CRONOANALISTA ', 92);
insert into tab_especialidade  (especialidade, id)  VALUES ('DATILOGRAFO ', 93);
insert into tab_especialidade  (especialidade, id)  VALUES ('DEMONSTRADOR ', 94);
insert into tab_especialidade  (especialidade, id)  VALUES ('DESENHISTA ', 95);
insert into tab_especialidade  (especialidade, id)  VALUES ('DESENHISTA PROJETISTA ', 96);
insert into tab_especialidade  (especialidade, id)  VALUES ('DESENHISTA TECNICO ', 97);
insert into tab_especialidade  (especialidade, id)  VALUES ('DESPACHANTE ', 98);
insert into tab_especialidade  (especialidade, id)  VALUES ('DIAGRAMADOR ', 99);
insert into tab_especialidade  (especialidade, id)  VALUES ('DIGITADOR ', 100);
insert into tab_especialidade  (especialidade, id)  VALUES ('DIRETOR DE EMPRESA ', 101);
insert into tab_especialidade  (especialidade, id)  VALUES ('DIRETOR DE EMPRESA DE COMERCIO VAREJISTA ', 102);
insert into tab_especialidade  (especialidade, id)  VALUES ('DIRETOR DE EMPRESA DE COMUNICACOES ', 103);
insert into tab_especialidade  (especialidade, id)  VALUES ('DIRETOR DE EMPRESA DE CONSTRUCAO CIVIL ', 104);
insert into tab_especialidade  (especialidade, id)  VALUES ('DIRETOR DE EMPRESA DE PRESTACAO DE SERVICOS ', 105);
insert into tab_especialidade  (especialidade, id)  VALUES ('DIRETOR DE EMPRESA DE SERVICOS CLINICOS E HOSPITALARES ', 106);
insert into tab_especialidade  (especialidade, id)  VALUES ('DIRETOR DE EMPRESA FINANCEIRA ', 107);
insert into tab_especialidade  (especialidade, id)  VALUES ('DIRETOR DE EMPRESA MANUFATUREIRA ', 108);
insert into tab_especialidade  (especialidade, id)  VALUES ('DIRETOR DE ESTABELECIMENTO DE ENSINO ', 109);
insert into tab_especialidade  (especialidade, id)  VALUES ('DIRETOR DE ESTABELECIMENTO DE ENSINO SUPERIOR ', 110);
insert into tab_especialidade  (especialidade, id)  VALUES ('DIRETORES DE EMPRESAS ', 111);
insert into tab_especialidade  (especialidade, id)  VALUES ('ECONOMISTA ', 112);
insert into tab_especialidade  (especialidade, id)  VALUES ('ECONOMISTA MERCADOLOGIA ', 113);
insert into tab_especialidade  (especialidade, id)  VALUES ('ECONOMISTA PROGRAMACAO ECONOMICO FINANCEIRA ', 114);
insert into tab_especialidade  (especialidade, id)  VALUES ('ECONOMISTAS ', 115);
insert into tab_especialidade  (especialidade, id)  VALUES ('EDITOR DE LIVROS ', 116);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENCARREGADO DE DIGITACAO E OPERACAO ', 117);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENFERMEIRO ', 118);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENFERMEIRO DO TRABALHO ', 119);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENFERMEIROS ', 120);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENGENHEIRO AERONAUTICO ', 121);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENGENHEIRO AGRONOMO ', 122);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENGENHEIRO CIVIL ', 123);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENGENHEIRO DE CONTROLE DE QUALIDADE ', 124);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENGENHEIRO DE MANUTENCAO ELETRICIDADE E ELETRONICA ', 125);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENGENHEIRO DE MINAS ', 126);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENGENHEIRO DE ORGANIZACAO E METODOS ', 127);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENGENHEIRO DE SEGURANCA DO TRABALHO ', 128);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENGENHEIRO DE TELECOMUNICACOES ', 129);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENGENHEIRO DE TRAFEGO ', 130);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENGENHEIRO ELETRICISTA ', 131);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENGENHEIRO ELETRONICO ', 132);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENGENHEIRO MECANICO ', 133);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENGENHEIRO QUIMICO ', 134);
insert into tab_especialidade  (especialidade, id)  VALUES ('ENGENHEIROS ', 135);
insert into tab_especialidade  (especialidade, id)  VALUES ('ESCRITURARIO ', 136);
insert into tab_especialidade  (especialidade, id)  VALUES ('ESCRIVAO ', 137);
insert into tab_especialidade  (especialidade, id)  VALUES ('ESTATISTICO ', 138);
insert into tab_especialidade  (especialidade, id)  VALUES ('ESTETICISTA ', 139);
insert into tab_especialidade  (especialidade, id)  VALUES ('FARMACEUTICO ', 140);
insert into tab_especialidade  (especialidade, id)  VALUES ('FISIOTERAPEUTA ', 141);
insert into tab_especialidade  (especialidade, id)  VALUES ('FONOAUDIOLOGO ', 142);
insert into tab_especialidade  (especialidade, id)  VALUES ('FUNCIONARIO PUBLICO ESTADUAL SUPERIOR ', 143);
insert into tab_especialidade  (especialidade, id)  VALUES ('FUNCIONARIO PUBLICO FEDERAL SUPERIOR ', 144);
insert into tab_especialidade  (especialidade, id)  VALUES ('FUNCIONARIO PUBLICO MUNICIPAL SUPERIOR ', 145);
insert into tab_especialidade  (especialidade, id)  VALUES ('FUNCIONARIO PUBLICO SUPERIOR ', 146);
insert into tab_especialidade  (especialidade, id)  VALUES ('GEOLOGO ', 147);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE ADMINISTRATIVO ', 148);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE COMERCIAL ', 149);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE BANCO ', 150);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE BAR ', 151);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE COMPRA ', 152);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE  EMPRESAS ', 153);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE HOTEL ', 154);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE INFORMATICA ', 155);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE LOJA ', 156);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE MARKETING ', 157);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE OPERACAO ', 158);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE PESQUISA E DESENVOLVIMENTO ', 159);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE PESSOAL ', 160);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE PLANEJAMENTO ', 161);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE POSTAL E TELECOMUNICACOES ', 162);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE PRODUCAO ', 163);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE PROPAGANDA ', 164);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE RESTAURANTE ', 165);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE RH ', 166);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE TRANSPORTE ', 167);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE DE VENDAS ', 168);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE EXECUTIVO ', 169);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE FINANCEIRO ', 170);
insert into tab_especialidade  (especialidade, id)  VALUES ('GERENTE OPERACIONAL ', 171);
insert into tab_especialidade  (especialidade, id)  VALUES ('INSPETOR DE PRODUCAO ', 172);
insert into tab_especialidade  (especialidade, id)  VALUES ('INSPETOR DE QUALIDADE ', 173);
insert into tab_especialidade  (especialidade, id)  VALUES ('INSPETOR DE	SERVICOS DE TRANSPORTE ', 174);
insert into tab_especialidade  (especialidade, id)  VALUES ('INSPETOR TECNICO DE VENDAS ', 175);
insert into tab_especialidade  (especialidade, id)  VALUES ('INSTRUTOR DE APRENDIZAGEM E TREINAMENTO ', 176);
insert into tab_especialidade  (especialidade, id)  VALUES ('JORNALISTA ', 177);
insert into tab_especialidade  (especialidade, id)  VALUES ('LABORATORISTA ANALISES CLINICAS ', 178);
insert into tab_especialidade  (especialidade, id)  VALUES ('LABORATORISTA INDUSTRIAL ', 179);
insert into tab_especialidade  (especialidade, id)  VALUES ('LOCUTOR ', 180);
insert into tab_especialidade  (especialidade, id)  VALUES ('MAITRE ', 181);
insert into tab_especialidade  (especialidade, id)  VALUES ('MEDICO ', 182);
insert into tab_especialidade  (especialidade, id)  VALUES ('MEDICO ANESTESISTA ', 183);
insert into tab_especialidade  (especialidade, id)  VALUES ('MEDICO CARDIOLOGISTA ', 184);
insert into tab_especialidade  (especialidade, id)  VALUES ('MEDICO DO TRABALHO ', 185);
insert into tab_especialidade  (especialidade, id)  VALUES ('MEDICO GINECOLOGISTA ', 186);
insert into tab_especialidade  (especialidade, id)  VALUES ('MEDICO ORTOPEDISTA ', 187);
insert into tab_especialidade  (especialidade, id)  VALUES ('MEDICO PEDIATRA ', 188);
insert into tab_especialidade  (especialidade, id)  VALUES ('MEDICO PSIQUIATRA ', 189);
insert into tab_especialidade  (especialidade, id)  VALUES ('MEDICO VETERINARIO ', 190);
insert into tab_especialidade  (especialidade, id)  VALUES ('MESTRE CONTRUCAO CIVIL ', 191);
insert into tab_especialidade  (especialidade, id)  VALUES ('MESTRE INDUSTRIAL ', 192);
insert into tab_especialidade  (especialidade, id)  VALUES ('MOTOCICLISTA TRANSPORTE DE MERCADORIAS ', 193);
insert into tab_especialidade  (especialidade, id)  VALUES ('MOTORISTA ', 194);
insert into tab_especialidade  (especialidade, id)  VALUES ('MOTORISTA DE CAMINHAO ', 195);
insert into tab_especialidade  (especialidade, id)  VALUES ('MOTORISTA DE FURGAO OU VEICULO SIMILAR ', 196);
insert into tab_especialidade  (especialidade, id)  VALUES ('MOTORISTA DE ONIBUS ', 197);
insert into tab_especialidade  (especialidade, id)  VALUES ('MOTORISTA DE TAXI ', 198);
insert into tab_especialidade  (especialidade, id)  VALUES ('MUSICO ', 199);
insert into tab_especialidade  (especialidade, id)  VALUES ('NUTRICIONISTA ', 200);
insert into tab_especialidade  (especialidade, id)  VALUES ('OPERADOR DE CAMERA DE TELEVISAO ', 201);
insert into tab_especialidade  (especialidade, id)  VALUES ('OPERADOR DE COMPUTADOR ', 202);
insert into tab_especialidade  (especialidade, id)  VALUES ('OPERADOR DE EQUIPAMENTOS DE ENTRADA DE DADOS ', 203);
insert into tab_especialidade  (especialidade, id)  VALUES ('OPERADOR DE ESTACAO DE RADIO ', 204);
insert into tab_especialidade  (especialidade, id)  VALUES ('OPERADOR DE MAQUINAS E VEICULOS ', 205);
insert into tab_especialidade  (especialidade, id)  VALUES ('OPERADOR DE MICRO ', 206);
insert into tab_especialidade  (especialidade, id)  VALUES ('OPERADOR DE PRODUTOS FINANCEIROS ', 207);
insert into tab_especialidade  (especialidade, id)  VALUES ('OPERADOR DE RAIOS X ', 208);
insert into tab_especialidade  (especialidade, id)  VALUES ('OPERADOR DE TELEMARKETING ', 209);
insert into tab_especialidade  (especialidade, id)  VALUES ('ORIENTADOR EDUCACIONAL ', 210);
insert into tab_especialidade  (especialidade, id)  VALUES ('OURIVES ', 211);
insert into tab_especialidade  (especialidade, id)  VALUES ('PEDAGOGO ', 212);
insert into tab_especialidade  (especialidade, id)  VALUES ('PILOTO ', 213);
insert into tab_especialidade  (especialidade, id)  VALUES ('PINTOR ', 214);
insert into tab_especialidade  (especialidade, id)  VALUES ('PRODUTOR DE RADIO E TELEVISAO ', 215);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE 1A A 4A SERIE ENSINO DE 1O GRAU ', 216);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE ADMINISTRACAO ENSINO SUPERIOR ', 217);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE ALUNOS COM DEFICENCIAS MENTAIS ', 218);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE BIOLOGIA ENSINO DE 2O GRAU ', 219);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE CIENCIAS NATURAIS ENSINO DE 1O GRAU ', 220);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE COMUNICACAO ', 221);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE CONTABILIDADE ENSINO SUPERIOR ', 222);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE DIDATICA ENSINO SUPERIOR ', 223);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE DIREITO ', 224);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE ECONOMIA ', 225);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE EDUCACAO FISICA ', 226);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE ENFERMAGEM ', 227);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE ENSINO PRE ESCOLAR ', 228);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE ESTATISTICA ', 229);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE ESTUDOS SOCIAIS ENSINO DE 1O GRAU ', 230);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE FISICA ', 231);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE FISIOTERAPIA ENSINO SUPERIOR ', 232);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE HISTORIA ', 233);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE INGLES ', 234);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE LINGUA PORTUGUESA ', 235);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE LINGUAS ESTRANGEIRAS ', 236);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE MATEMATICA ', 237);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE ORIENTACAO EDUCACIONAL ENSINO SUPERIOR ', 238);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE PEDAGOGIA ', 239);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE PORTUGUES E LITERATURA ', 240);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE PRATICA DE ENSINO ENSINO SUPERIOR ', 241);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE PSICOLOGIA ', 242);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE QUIMICA ', 243);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE SOCIOLOGIA ', 244);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSOR DE TECNOLOGIA ', 245);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSORES ', 246);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSORES DE BIOLOGIA ', 247);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSORES DE CIENCIAS HUMANAS ', 248);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSORES DE ENSINO DE 2O GRAU ', 249);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSORES DE ENSINO DE PRIMEIRO GRAU ', 250);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSORES DE ENSINO ESPECIAL ', 251);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSORES DE ENSINO PRE ESCOLAR ', 252);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSORES DE ENSINO SUPERIOR ', 253);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSORES DE PEDAGOGIA ', 254);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROFESSSOR DE GEOGRAFIA ', 255);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROGRAMADOR DE COMPUTADOR ', 256);
insert into tab_especialidade  (especialidade, id)  VALUES ('PROPAGANDISTA DE PRODUTOS DE LABORATORIO ', 257);
insert into tab_especialidade  (especialidade, id)  VALUES ('PSICOLOGO ', 258);
insert into tab_especialidade  (especialidade, id)  VALUES ('QUIMICO ', 259);
insert into tab_especialidade  (especialidade, id)  VALUES ('QUIMICO ANALISTA ', 260);
insert into tab_especialidade  (especialidade, id)  VALUES ('QUIMICO INDUSTRIAL ', 261);
insert into tab_especialidade  (especialidade, id)  VALUES ('RECEPCIONISTA ', 262);
insert into tab_especialidade  (especialidade, id)  VALUES ('REDATOR ', 263);
insert into tab_especialidade  (especialidade, id)  VALUES ('RELACOES PUBLICAS ', 264);
insert into tab_especialidade  (especialidade, id)  VALUES ('REPORTER ', 265);
insert into tab_especialidade  (especialidade, id)  VALUES ('REPRESENTANTE COMERCIAL ', 266);
insert into tab_especialidade  (especialidade, id)  VALUES ('SECRETARIO ', 267);
insert into tab_especialidade  (especialidade, id)  VALUES ('SECRETARIO BILINGUE ', 268);
insert into tab_especialidade  (especialidade, id)  VALUES ('SECRETARIO EXECUTIVO ', 269);
insert into tab_especialidade  (especialidade, id)  VALUES ('SERVENTUARIOS DA JUSTICA ', 270);
insert into tab_especialidade  (especialidade, id)  VALUES ('SOCIOLOGO ', 271);
insert into tab_especialidade  (especialidade, id)  VALUES ('SUPERVISOR DE COMPRAS ', 272);
insert into tab_especialidade  (especialidade, id)  VALUES ('SUPERVISOR DE VENDAS COMERCIO ATACADISTA ', 273);
insert into tab_especialidade  (especialidade, id)  VALUES ('SUPERVISOR DE VENDAS COMERCIO VAREJISTA ', 274);
insert into tab_especialidade  (especialidade, id)  VALUES ('SUPERVISOR EDUCACIONAL ', 275);
insert into tab_especialidade  (especialidade, id)  VALUES ('SUPERVISORES DE COMPRAS E COMPRADORES ', 276);
insert into tab_especialidade  (especialidade, id)  VALUES ('SUPERVISORES DE VENDAS ', 277);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO ', 278);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO AGRICOLA ', 279);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO AGROPECUARIO ', 280);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO DE ADMINISTRACAO ', 281);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO DE CONTABILIDADE ', 282);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO DE ENFERMAGEM ', 283);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO DE LABORATORIO ', 284);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO DE MANUTENCAO ELETRICA ', 285);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO DE MANUTENCAO ELETRONICA ', 286);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO DE OBRAS CIVIS ', 287);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO DE PLANEJAMENTO DE PRODUCAO ', 288);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO DE SEGURANCA DO TRABALHO ', 289);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO DE SEGUROS ', 290);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO DE TELECOMUNICACOES ', 291);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO ELETRONICO ', 292);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO MECANICO ', 293);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO MECANICO MAQUINAS ', 294);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO METALURGICO ', 295);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICO QUIMICO ', 296);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICOS DE BIOLOGIA  ', 297);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICOS DE ELETRICIDADE ', 298);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICOS DE ENFERMAGEM ', 299);
insert into tab_especialidade  (especialidade, id)  VALUES ('TECNICOS DE OBRAS CIVIS ', 300);
insert into tab_especialidade  (especialidade, id)  VALUES ('TERAPEUTA OCUPACIONAL ', 301);
insert into tab_especialidade  (especialidade, id)  VALUES ('TOPOGRAFO ', 302);
insert into tab_especialidade  (especialidade, id)  VALUES ('TRABALHADORES DAS PROFISSOES CIENTIFICAS ', 303);
insert into tab_especialidade  (especialidade, id)  VALUES ('TRABALHADORES DE COMERCIO ', 304);
insert into tab_especialidade  (especialidade, id)  VALUES ('TRABALHADORES DE SERVICOS ADMINISTRATIVOS ', 305);
insert into tab_especialidade  (especialidade, id)  VALUES ('TRABALHADORES DE SERVICOS DE CONTABILIDADE ', 306);
insert into tab_especialidade  (especialidade, id)  VALUES ('TRABALHADORES DE SERVICOS DE TURISMO ', 307);
insert into tab_especialidade  (especialidade, id)  VALUES ('VENDEDOR A DOMICILIO ', 308);
insert into tab_especialidade  (especialidade, id)  VALUES ('VENDEDOR AMBULANTE ', 309);
insert into tab_especialidade  (especialidade, id)  VALUES ('VENDEDOR DE COMERCIO ATACADISTA ', 310);
insert into tab_especialidade  (especialidade, id)  VALUES ('VENDEDOR DE COMERCIO VAREJISTA ', 311);
insert into tab_especialidade  (especialidade, id)  VALUES ('VENDEDOR PRACISTA ', 312);
insert into tab_especialidade  (especialidade, id)  VALUES ('VENDEDORES DE COMERCIO ATACADISTA E VAREJISTA ', 313);
insert into tab_especialidade  (especialidade, id)  VALUES ('VENDEDORES PRACISTAS ', 314);
insert into tab_especialidade  (especialidade, id)  VALUES ('VEREADOR ', 315);
insert into tab_especialidade  (especialidade, id)  VALUES ('ZOOTECNISTA', 316);
